In [2]:
import pandas as pd

data = {'Salary':[20000,22000,25000,27000,30000,500000]}
df = pd.DataFrame(data)

In [3]:
df.describe()

              Salary
count       6.000000
mean   104000.000000
std    194031.956131
min     20000.000000
25%     22750.000000
50%     26000.000000
75%     29250.000000
max    500000.000000

In [4]:
df.shape

(6, 1)

In [5]:
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(lower, upper)

13000.0 39000.0

In [ ]:
outliers = df[(df['Salary'] < lower) | (df['Salary'] > upper)]
print(outliers)

Step 5: Handle outliers (3 main methods) 🧠

Method A: Remove outliers 🗑️
Method B: Capping / Winsorization ✂️
Method C: Log transformation 📉

In [6]:
df_clean = df[(df['Salary'] >= lower) & (df['Salary'] <= upper)]

In [7]:
df_clean.shape

(5, 1)

In [8]:
df_clean.describe()

             Salary
count      5.000000
mean   24800.000000
std     3962.322551
min    20000.000000
25%    22000.000000
50%    25000.000000
75%    27000.000000
max    30000.000000

In [9]:
df_clean.head()

   Salary
0   20000
1   22000
2   25000
3   27000
4   30000

In [10]:
df['Salary'] = df['Salary'].clip(lower, upper)

In [12]:
import numpy as np

df['Salary_log'] = np.log(df['Salary'])